### Create a channel (auth)
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
x-token: {{token}}
x-refresh-token: {{refreshToken}}

mutation Mutation($teamId: Int!, $name: String!) {
  createChannel(teamId: $teamId, name: $name) {
    ok
    channel {
      id
      name
    }
    errors {
      path
      message
    }
  }
}

{
    "teamId": 2,
    "name": "old-team"
}