@teamName = bungee-team

### Create team (auth)
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
x-token: {{token}}
x-refresh-token: {{refreshToken}}

mutation CreateTeam($name: String!) {
  createTeam(name: $name) {
    ok
    team {
      id
      name
    }
    errors {
      path
      message
    }
  }
}

{
    "name": "{{teamName}}"
}

### Create team (unauth)
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation CreateTeam($name: String!) {
  createTeam(name: $name) {
    ok
    errors {
      path
      message
    }
  }
}

{
    "name": "{{teamName}}"
}

### Get all teams
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
x-token: {{token}}
x-refresh-token: {{refreshToken}}

query GetAllTeams{
  allTeams {
    id
    name
    channels {
      name
    }
  }
}

### Invite to the team
POST http://localhost:4000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
x-token: {{token}}
x-refresh-token: {{refreshToken}}

mutation AddTeamMember($teamId: Int!, $email: String!) {
  addTeamMember(teamId: $teamId, email: $email) {
    ok
    errors {
      path
      message
    }
  }
}

{
    "email": "linh@gmail.com",
    "teamId": 1
}